/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import java.awt.Color;
import java.awt.Graphics;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author alumno
 */
public class Fractal extends javax.swing.JFrame {

    private static int angulo = 90;
    
    public Fractal() {
        super("Arbol Fractal");
        initComponents();
        setBounds(100, 100, 800, 600);
        setResizable(false);
        this.getContentPane().setBackground(Color.black);
        this.getContentPane().setIgnoreRepaint(true);
        this.setVisible(true);
    }
    
    private void dibujaFractal(Graphics g,int x1,int y1, double angulo, int longitud){
        if(longitud == 0){
            return;
        }

        int x2 = x1 + (int) (longitud*Math.cos(Math.toRadians(angulo)));
        int y2 = y1 + (int) (longitud*Math.sin(Math.toRadians(angulo)));
        g.drawLine(x1, y1, x2, y2);
        dibujaFractal(g,x2,y2,angulo-20,longitud-5);
        dibujaFractal(g,x2,y2,angulo+20,longitud-5);
        
    }
    
    @Override
    public void paint(Graphics g){
        super.paint(g);
        g.setColor(Color.red);
        dibujaFractal(g,400,300,angulo,50);
        g.setColor(Color.orange);
        dibujaFractal(g,400,300,angulo+60,50);
        g.setColor(Color.yellow);
        dibujaFractal(g,400,300,angulo+120,50);
        g.setColor(Color.green);
        dibujaFractal(g,400,300,angulo+180,50);
        g.setColor(Color.blue);
        dibujaFractal(g,400,300,angulo+240,50);
        g.setColor(new Color(87,35,100));
        dibujaFractal(g,400,300,angulo+300,50);
        
        
        /*QUITA ESTE COMENTARIO PARA AÑADIR UN DELAY DE TIEMPO
        try{
                TimeUnit.SECONDS.sleep(1);
        }
        catch(InterruptedException e){
            e.printStackTrace();
        }
        */
        
        /*QUITA ESTE COMENTARIO PARA QUE GIRE
        angulo += 45;
        this.repaint();
        */

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fractal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fractal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fractal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fractal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fractal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
